// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlodlclxsnddtgpgurav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsb2RsY2x4c25kZHRncGd1cmF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NjEwNjYsImV4cCI6MjA1NzMzNzA2Nn0.vdOr3hXG2ZQTks7jrAv66h9h-HmSeIXbGEloJKS9TeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);